project:
  type: book
  output-dir: docs

book:
  title: "Script for data science"
  author: "donata boric"
  downloads: [docx]
  repo-url: https://github.com/bodonat/data-science-script
  repo-actions: [edit, issue]
  chapters:
    - index.qmd
    - part: "First part: Python"
      chapters:
          - python_intro.ipynb
          - handling_exceptions.ipynb
          - oop.ipynb
          - useful_functions.ipynb
          - python_modules.ipynb
          
    - part: "Second part: Data Science"
      chapters:
          - ds_intro.ipynb
          - statistics.ipynb
          - tsa.ipynb
          - machine_learning.ipynb
          - deep_learning.ipynb
        
    - summary.qmd
    - references.qmd

bibliography: references.bib

format:
  html:
    theme: cosmo
    toc: true
    toc-title: On this page
    code-fold: true
    code-tools: true
  docx: default





