project:
  type: book
  output-dir: docs

book:
  title: "Script for data science"
  author: "donata boric"
  chapters:
    - index.qmd
    - intro.qmd
    - part: "Chapters"
      chapters:
          - section1.ipynb
          - section2.ipynb
    - summary.qmd
    - references.qmd

bibliography: references.bib

format:
  html:
    theme: cosmo
  docx: default





